[2025-09-30 06:00:14] INFO root: init_logging: logfile=logs\log_20250930_040014.txt
[2025-09-30 06:00:14] INFO __main__: Logging initialized
[2025-09-30 06:00:17] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2369, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2364, in main
    app = TradingAppExtended(root)
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 399, in __init__
    self._build_ui()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 786, in _build_ui
    self._init_ui_logging(parent_frame)  # parent_frame = frame que contiene el notebook
NameError: name 'parent_frame' is not defined
