[2025-10-02 00:56:41] INFO root: init_logging: logfile=logs\log_20251001_225641.txt
[2025-10-02 00:56:41] INFO __main__: Logging initialized
[2025-10-02 00:56:44] INFO root: Config loaded from config\gui_config.json
[2025-10-02 00:56:44] ERROR __main__: DB writer failed to start
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 633, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined
[2025-10-02 00:56:44] ERROR root: DB writer failed to start:
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 633, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined

[2025-10-02 01:16:05] INFO root: Websocket closed by user.
[2025-10-02 01:16:06] INFO root: Websocket URL empty.
[2025-10-02 01:18:38] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3047, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3043, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
