[2025-09-30 06:19:03] INFO root: init_logging: logfile=logs\log_20250930_041903.txt
[2025-09-30 06:19:03] INFO __main__: Logging initialized
[2025-09-30 06:25:24] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2373, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2369, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
