[2025-10-01 17:59:55] INFO root: init_logging: logfile=logs\log_20251001_155955.txt
[2025-10-01 17:59:55] INFO __main__: Logging initialized
[2025-10-01 17:59:58] INFO root: Config loaded from config\gui_config.json
[2025-10-01 18:00:03] INFO root: No dataframe available for preview: scaled
[2025-10-01 18:00:56] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2722, in <module>
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2718, in main
    try:
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
