[2025-10-02 02:14:13] INFO root: init_logging: logfile=logs\log_20251002_001413.txt
[2025-10-02 02:14:13] INFO __main__: Logging initialized
[2025-10-02 02:14:15] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3041, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3036, in main
    app = TradingAppExtended(root)
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 433, in __init__
    self._build_ui()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 1273, in _build_ui
    self._build_status_tab()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 1406, in _build_status_tab
    btn_ws_panel = Button(frm_controls, text="Open WS Panel", command=self._open_ws_panel())
AttributeError: 'TradingAppExtended' object has no attribute '_open_ws_panel'
