[2025-10-02 00:52:37] INFO root: init_logging: logfile=logs\log_20251001_225237.txt
[2025-10-02 00:52:37] INFO __main__: Logging initialized
[2025-10-02 00:52:43] INFO root: Config loaded from config\gui_config.json
[2025-10-02 00:52:43] ERROR __main__: DB writer failed to start
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 633, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined
[2025-10-02 00:52:43] ERROR root: DB writer failed to start:
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 633, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined

[2025-10-02 00:53:18] INFO websocket: Websocket connected
[2025-10-02 00:53:18] INFO root: WS open (callback)
[2025-10-02 00:53:56] INFO root: WS closed: None None
[2025-10-02 00:53:56] INFO root: Websocket closed by user.
[2025-10-02 00:54:03] INFO websocket: Websocket connected
[2025-10-02 00:54:03] INFO root: WS open (callback)
[2025-10-02 00:55:13] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3047, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 3043, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
