[2025-10-02 03:23:22] INFO root: init_logging: logfile=logs\log_20251002_012322.txt
[2025-10-02 03:23:22] INFO __main__: Logging initialized
[2025-10-02 03:23:25] INFO root: Config loaded from config\gui_config.json
[2025-10-02 03:23:44] INFO websocket: Websocket connected
[2025-10-02 03:23:45] INFO root: WS open (callback)
[2025-10-02 03:27:52] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2887, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2883, in main
    root.mainloop()
  File "C:\Users\soyko\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
